---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: ashtonc-test-gdb-rd-pvc
        labels:
                username: ashtonc
                env: test
spec:
        accessModes:
                - ReadWriteOnce
        storageClassName: cinder-csi
        resources:
                requests:
                        storage: 1Gi
